sudo: required

# https://docs.travis-ci.com/user/languages/cpp/
# Since there is no Bash language support, using C++, since Travis does no
# default installation.
# FIXME: do a PDF building in a supported language.
language: cpp

services:
  - docker

before_install:
  - docker pull jagregory/pandoc

script:
  - "./markdown_pdf.sh craig_astill_cv.md"

deploy:
  provider: releases
  api_key:
    secure: SNN6rkHJhjNCbkGQkqo3+7Z5KdWO3QU7oOPCQ43CKYUdXpRbBcOTARwHBfz0kgI30hIW9HeG1tvx4jcbM54PSTTwPZFi3lDMv7XxZgANTAOxHABNjEPZPXa3rrz+sMD+mYyekDnCAeRkmQSLMxYbeJHUdURAAjXG2JZON6EDT8ZYy5dAqohbKoOlZTLH6ATOKiZz8EElSiy2z84U7KevNv1ThVer3mpsKS9e27QeEWD6fXCKMErVY8PlKi3pch1Ohrxl1X4avuyO4aJfKT40rYi64dMY88flYItTUp/kHUMTFVCgqq/ORdp/0iWRoJ8fBtoHSuL2uud2bDs4gNUXUXDG7oNz2eL0UQUK+YgaYTxPZDNFNnsdNfEFWmW5FUH/TVWvUf2laOcR1vHp2wklxmgMuYwyQnTcdceBV9JIubvnAJXa5Rt/WW+kF5mKSUc/NGcDmDgiYoZna+wh8ks9uZ0QorCXhMVXzP5xmGcDCQinaBDCgZ85Ry6qkykLhWORj9thgF3z1eu3FcQz1Y7uU4Xz9lauUC4HIo7nAgpvuxxgFXtJq6AuC4W8y8gphf0DrP1iI824gNRBijqduoQgZn01zjiOQapm+uvNDGXPBKLmCVJRn9BRqXuALnVOr5lxg7OD0YSxrg9wksDQRfSK4P3zMt4m3V3hIsDN1QcXZzA=
  file: craig_astill_cv.pdf
  skip_cleanup: true
  on:
    repo: jackson15j/cv
    branch: travis
