# https://taskfile.dev
version: '3'

output: prefixed

env:
  GITHUB_TOKEN: unset

vars:
  DOCKER_IMAGE: pandoc/latex

tasks:
  docker-pull:
    internal: true
    cmds:
      - docker pull {{.DOCKER_IMAGE}}

  generate-pdf:
    deps:
      - docker-pull
    summary: |
      Generate my CV

      This task will pull down the latest pandoc docker image and use that to
      generate a new CV PDF.
    cmds:
      - docker run -v "$(pwd):/data" --user $(id -u):$(id -g) {{.DOCKER_IMAGE}} craig_astill_cv.md metadata.yaml layout.yaml -o craig_astill_cv.pdf
      - echo "Generated PDF"
    sources:
      - craig_astill_cv.md
      - ./*.yaml
    generates:
      - craig_astill_cv.pdf

  semantic-release:
    summary: Tag Github based off semantic commits.
    dotenv: ['.env',]
    cmds:
      - echo $GITHUB_TOKEN
      - docker build . -t semantic-release-cv
      - docker run --rm --name srcv -e GITHUB_TOKEN -v "${PWD}":/app  -v ~/.ssh:/root/.ssh/ semantic-release-cv --debug -d
