name: Release

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]
  pull_request:
    branches: [ master ]
  # push:
  #   tags:
  #   - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/download-artifact@master
        with:
          name: pdf-cv
          path: craig_astill_cv.pdf
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.pdf"
          token: ${{ secrets.GITHUB_TOKEN }}
