name: Release

on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Generate PDF
        run: task generate-pdf

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.pdf"
          token: ${{ secrets.GITHUB_TOKEN }}

      # TODO: consolidate Semantic Version + Above PDF artefact generation!
      - name: Semantic Release
        run: task semantic-release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
